kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
     - name: course
       valueFrom:
         configMapKeyRef:
           name: nginx-config # name of the configmap your refering
           key: course # env.name and config map key name can be differnet
     - name: duration
       valueFrom:
         configMapKeyRef:
           name: nginx-config
           key: duration
